apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate1
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate1
  template:
    metadata:
      labels:
        app: inflate1
        az-spread: oke
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate1
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1
      nodeSelector:
        eks-immersion-team: my-team
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              az-spread: oke
      